### ISSUE TITLE
Crash when trying to write to Console.app

### ISSUE THREAD

**Issue by latenitefilms** [steven-joruk/oslog#3] opened 2022-12-15 01:01 UTC
Full disclosure, I'm totally new to Rust, and really have no idea what I'm doing.

I'm trying to integrate some Rust code into an Objective-C project, and was hoping to use `oslog` to write some debug messages to macOS's Console.app.

I've added this to my Cargo file:

```
[dependencies]
log = "0.4.17"
oslog = "0.2.0"
```

I've added this to my Rust code:

```rust
extern crate log;
extern crate oslog;

oslog::OsLogger::new("com.latenitefilms.GyroflowForFinalCutPro")
       .level_filter(log::LevelFilter::Debug)
       .category_level_filter("Settings", log::LevelFilter::Trace)
       .init()
       .unwrap();

log::debug!("[Gyroflow] Debug");
```

...but it just crashes.

Any tips or tricks as to what I'm doing wrong?

**Comment by steven-joruk** [comment] 2022-12-15 01:47
I'm unable to reproduce this. Which version of macOS and rustc are you using? I suppose it could also be related to which C compiler cargo is using to build the wrapper.

Please can you share the crash log?

**Comment by mmbarness** [comment] 2023-04-05 00:57
Hey, I'm having a related problem. Here's the compilation output.
```
The following warnings were emitted during compilation:

warning: wrapper.c:1:10: fatal error: os/log.h: No such file or directory
warning:     1 | #include <os/log.h>
warning:       |          ^~~~~~~~~~
warning: compilation terminated.

error: failed to run custom build command for `oslog v0.2.0`

Caused by:
  process didn't exit successfully: `<app_filepath>/target/debug/build/oslog-42bda0a965460c75/build-script-build` (exit status: 1)
  --- stdout
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("0")
  HOST = Some("x86_64-unknown-linux-gnu")
  cargo:rerun-if-env-changed=CC_x86_64-unknown-linux-gnu
  CC_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CC_x86_64_unknown_linux_gnu
  CC_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CC
  HOST_CC = None
  cargo:rerun-if-env-changed=CC
  CC = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64-unknown-linux-gnu
  CFLAGS_x86_64-unknown-linux-gnu = None
  cargo:rerun-if-env-changed=CFLAGS_x86_64_unknown_linux_gnu
  CFLAGS_x86_64_unknown_linux_gnu = None
  cargo:rerun-if-env-changed=HOST_CFLAGS
  HOST_CFLAGS = None
  cargo:rerun-if-env-changed=CFLAGS
  CFLAGS = None
  cargo:rerun-if-env-changed=CRATE_CC_NO_DEFAULTS
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("true")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,llvm14-builtins-abi,sse,sse2")
  running: "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "/home/mmbarnes/programming/rusty-hooks/target/debug/build/oslog-c5686730c76129ea/out/wrapper.o" "-c" "wrapper.c"
  cargo:warning=wrapper.c:1:10: fatal error: os/log.h: No such file or directory
  cargo:warning=    1 | #include <os/log.h>
  cargo:warning=      |          ^~~~~~~~~~
  cargo:warning=compilation terminated.
  exit status: 1

  --- stderr


  error occurred: Command "cc" "-O0" "-ffunction-sections" "-fdata-sections" "-fPIC" "-gdwarf-4" "-fno-omit-frame-pointer" "-m64" "-Wall" "-Wextra" "-o" "<app_filepath>/target/debug/build/oslog-c5686730c76129ea/out/wrapper.o" "-c" "wrapper.c" with args "cc" did not execute successfully (status code exit status: 1).


warning: build failed, waiting for other jobs to finish...
```

**Comment by steven-joruk** [comment] 2023-04-05 10:26
Hi @mmbarness, your compiler isn't able to find `os/log.h` because your host and target are Linux. You'll need to compile this on macOS, or have access to macOS's SDK and cross-compile.

I'll add an example GitHub workflow to this repo and compile time check for the target. I'll close this but feel free to open another issue if you can't get it to work.

@latenitefilms if you get that crash log please let me know, I'd like to know what happened.

Thanks.

**Closed as completed** 2023-04-05 10:27 UTC

**Comment by mmbarness** [comment] 2023-04-05 12:21
Gotcha, would appreciate an example.
